main: com.raeic.embarker.Embarker
name: Embarker
version: 1
description: Custom plugin for Embarker Minecraft server
api-version: 1.15
load: STARTUP
author: Taurhuzz
website: https://raeic.com
depend: [WorldGuard]
commands:
  stake:
    description: Stake a chunk of land
    usage: /<command>
  unstake:
    description: Unstake a chunk of land
    usage: /<command>