# Rename this to config.yml and fill with your actual DB credentials.
# Do NOT check config.yml into Git.
db:
  driver: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://localhost/database_name"
  username: "root"
  password: "password"